### ISSUE TITLE
first login with new user fails

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#11]
Rather than a prompt to login and change password, I get
`InvalidPasswordException: password does not conform to policy: Password not long enough`
Yet the initial password I have set is long enough and otherwise conforms to the policy I've set (and I tried temporarily relaxing it). It's not an incorrect password (that correctly throws up an incorrect password error).

**Comment by talltom** [comment]
@matthewberryman see email.
New password is hard coded as a hack while we build out further password UI. The placeholder password doesn't match our policy. Will work on updated UI today and remove this hard coded hack. Sorry for confusion.

https://github.com/usergroupcoop/msf-reach/blob/master/public/login/login.js#L56

**Comment by talltom** [comment]
@matthewberryman now fixed - b9b5ce7ae64fec1d769bbc281f864b9c42b99265
At first login, user will be prompted to create a new password.

Note that we don't currently support other account changes, such as password reset.
