### ISSUE TITLE
reports details

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#14]
What do we need here exactly?
@talltom to comment on what's required, @mehrdadgit to complete.

**Comment by talltom** [comment]
- location (either from HTML5 geolocation or manually from the map)
- description (text)
- report tags (text - e.g. #disaster)
- username / alias (text)
- image

**Comment by matthewberryman** [comment]
Leave off tags / categories for now. Just username/alias, image, description.

**Comment by mehrdadgit** [comment]
just confirming the above will all go into "content" field as JSON ? (there will be no schema/api change ? ) and image is the link to the image uploaded to S3 ?

**Comment by talltom** [comment]
Hi @mehrdadgit, yes the majority of data goes in "content" field but location is stored separately by schema. For example:

```javascript
  .send({
  "eventId": eventId,
  "status": "confirmed",
  "created": "2017-05-22T20:35Z",
  "reportkey": '123',
  "location":{
    "lat":-6.10,
    "lng":108.7
  },
  "content":{
    "user":"integrated tester",
    "report_tags":"tags",
    "username/alias":"",
    "description":""
    "image_link": ""
  }
```
