### ISSUE TITLE
report cards require image

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#17]
Should make this optional I guess

**Comment by talltom** [comment]
Agreed. Images should be optional.

**Comment by matthewberryman** [comment]
@LucieGueuning absence of an image will cause the hang on report submission, once the image is made optional that hang issue will go away.

**Comment by matthewberryman** [comment]
@mehrdadgit Don't forget to update the card text to make it clear that this is optional, and test that it isn't required for successful card submission.

Since the database is currently offline I am doing a couple of speed tweeks that will take a bit longer. About another 10 mins until it's back online.
