### ISSUE TITLE
Express API cache is not functioning?

### ISSUE THREAD

**Issue by talltom** [usergroupcoop/msf-reach#27]
The endpoints /hazards relies on caching to reduce server load.

I have a hunch that the cache was not operating because when I run server locally I get:
`[apicache] bypass detected, skipping cache.`

I added a timestamp to this endpoint to verify. The timestamp updates with every call, which according to apicache docs it shouldn't

Possibly due to this:
https://github.com/kwhitley/apicache#user-content-client-side-bypass

**Comment by matthewberryman** [comment]
@talltom need me to set CACHE env var to true on EB? Currently unset (i.e. defaults to false)

**Comment by talltom** [comment]
probably? I wasn't around when we started using this so not sure on config.

**Comment by matthewberryman** [comment]
Set CACHE='true' in config, tested in a different browser that I'd not loaded msf-reach on before (to avoid any browser caching) and got back the same timestamp.
