### ISSUE TITLE
check report card wording

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#35]
https://docs.google.com/spreadsheets/d/1fGuGeet2TKD6Pxy8xm1jHEn1ujxZMWPIqeIUSV7VmCQ/edit#gid=203260487

**Comment by mehrdadgit** [comment]
doing this; in the spreadsheet says Free text (150 words) does it mean 150 chars ? should I enforce it ?

**Comment by matthewberryman** [comment]
Yes please add some JS code to validate client side (but: after all other work on this issue is complete)
