### ISSUE TITLE
event icons based on event type, on landing page map

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#42]
https://drive.google.com/drive/folders/0Bw27FPU-gFxYRkQ0aFZOaFAtVDg

**Comment by mehrdadgit** [comment]
Just wondering if they mean these icons: 
https://drive.google.com/drive/folders/0Bw27FPU-gFxYQmRyRVJ6MDBfdDQ
That folder does seem to have map-marker symbols ?

**Comment by matthewberryman** [comment]
No, definitely these ones https://drive.google.com/drive/folders/0Bw27FPU-gFxYRkQ0aFZOaFAtVDg as they're for different event types (no, they're not really map markers, but use them anyway). The other ones you linked are for different contact types (to be discussed another time)
