### ISSUE TITLE
Twitter search

### ISSUE THREAD

**Issue by anexact** [usergroupcoop/msf-reach#44]
Twitter Search function glitches in several ways:
1) no way to refresh the search, thus new information in Twitter, especially from peers, cannot be detected and thus cannot receive Reach-Out report card; if the search cannot be refreshed, it does not allow the operator to pick up latest info from peers who are requesting report cards;
2) seems to be a bit of trouble with the search finding relevant tweets, included those with precisely matching terms to the search bar; I'm not able to determine why or how it is missing them, but it finds some terms and not others—public API issue maybe;
3) when using refresh on the page in Chrome, it just takes you back to the Event Tab, but doesn't reload the tweets.

**Comment by matthewberryman** [comment]
1. You can click on the search button again. 
2. @talltom can comment on public API in more detail but from memory it's fairly limited (limited by number returned for each API call IIRC), can't do much about this short of some gnip work?
3. See 1.

Closing this unless anyone has better UI suggestions re 1 & 3?
