### ISSUE TITLE
date and nationality pickers on contact card can't be seen - text is white

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#47]
refer jquery-ui for datepicker css
refer https://github.com/usergroupcoop/country-select-js for nationality selector css

**Comment by matthewberryman** [comment]
https://github.com/usergroupcoop/country-select-js/blob/master/src/scss/countrySelect.scss is the source css file - you now have RW permissions to modify that, to build you need gulp installed and then run `npm install && gulp build`, then copy over the minified css to msf-reach.

**Comment by mehrdadgit** [comment]
No need @matthewberryman pushed a fix ...
