### ISSUE TITLE
PDC icon?

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#53]
If @anexact and @LucieGueuning can supply one I can put it in.

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/29506739-d6c37880-867f-11e7-8ee7-035955ce14b0.png)
The icons are the standard ones from PDC layers

**Comment by matthewberryman** [comment]
Ok the trouble is that the PDC map only has icons for current events and the image URLs are generated on the fly. So, I don't have access to the full set, nor can I grab them by systematically generating the image URLs to grab them from their server. In particular, the full set includes different colour borders for the icons depending on status. For now, I have gone with a limited subset that covers off on most of the disaster types, I hope, and ignores the status (i.e. when you look at the map, ignore the colour of the border). Someone will need to write to PDC and ask for the full set of icons (with their permission), then I can use the status field.

**Comment by matthewberryman** [comment]
closing as covered by #63
