### ISSUE TITLE
Request correction to Login tab in browser 

### ISSUE THREAD

**Issue by anexact** [usergroupcoop/msf-reach#56]
![image](https://user-images.githubusercontent.com/20785542/29508670-edd1ab66-8687-11e7-94a8-4c4697e67a6d.png)
Request to change this to: 
Login to MSF RESEACH

**Comment by anexact** [comment]
Also, request to add a Favicon on the browser tabs.

**Comment by matthewberryman** [comment]
You mean MSF REACH? Let me know what icon you want as a favicon and send in at least 16x16, 32x32 and 96x96 px sizes as per https://sympli.io/blog/2017/02/15/heres-everything-you-need-to-know-about-favicons-in-2017/

**Comment by anexact** [comment]
Okay, requested to MSF, will upload asap.

**Comment by matthewberryman** [comment]
https://drive.google.com/drive/folders/0Bw27FPU-gFxYc1huQ3BKWVZwRW8?usp=sharing
