### ISSUE TITLE
Name of event on landing page

### ISSUE THREAD

**Issue by LucieGueuning** [usergroupcoop/msf-reach#61]
Event Name should be set thanks to the following metadata: 
1. TYPE OF EMERGENCY (when created an event - basic information e.g. Typhoon)
2. LOCATION (when created an event - basic information - Map driven)
3. DATE AND TIME OF EMERGENCY (when created an event - basic information)

e.g. Event Name : Thyphoon_Bandung_21.08.2017
different from Event ID

This name can be editable with free text option on event level.

**Comment by LucieGueuning** [comment]
Twitter feed will take this automatic event name.

**Comment by matthewberryman** [comment]
Closing, captured in #30
