### ISSUE TITLE
Image on landing page

### ISSUE THREAD

**Issue by LucieGueuning** [usergroupcoop/msf-reach#64]
Fix image (stretched and not center) or delete entirely 

e.g. https://diggr.msf.org/loginPage#/

**Comment by matthewberryman** [comment]
The image can't be made smaller, as then I won't be able to read the text. It can't be made bigger without making the menu itself bigger. It's scaled to be in the same proportions and looks Ok to me, but since you're not happy, and since it's fiddly to move to the centre, I will delete.

**Comment by matthewberryman** [comment]
Also an issue on events page too.
