### ISSUE TITLE
Icons size

### ISSUE THREAD

**Issue by LucieGueuning** [usergroupcoop/msf-reach#71]
average size : 
![image](https://user-images.githubusercontent.com/25951555/29548581-8cc542b2-8734-11e7-8d79-976f747aa9a2.png)

Could you please put up icons up by 150? (Reports icon ; Mission histories icon ; Current event icon ; volcano PDC icons 2 on Indonesia). 

Also could you please refer to ticket#63 for updating the icon for Mission histories (Christina link)?

**Comment by matthewberryman** [comment]
@LucieGueuning I will fix sizes tomorrow a.m. See #63 for mission history icon issue—I had the existing one in place and need one to fix the problems that will only grow bigger as I increase the size for this issue ticket.

**Comment by LucieGueuning** [comment]
@clgeros May I ask you your opinion for design (icons size)? and try to reply to Matthew comments? 
Many thanks

**Comment by clgeros** [comment]
@matthewberryman @LucieGueuning icon size is better I think... could be reduced by maybe 20%? If that's do-able..

**Comment by clgeros** [comment]
One additional check: is the location of the icon set to be the end point of the bubble? It should be and appears as so when you zoom in, but when zoomed out, the icons do appear "off-location"... may or may not be able to correct this now. So just checking.

**Comment by matthewberryman** [comment]
20% across the board?

**Comment by clgeros** [comment]
I think so

**Comment by clgeros** [comment]
i'm actually torn. they might be fine as they are.

**Comment by matthewberryman** [comment]
Let's just leave it then. I think icons are centred on the location so if there's a point in the icon (outside of the centre of the icon) that needs to be on the location, then it will be a bit offset without tweaks (not sure if this is doable with leaflet but will explore that in a new ticket).

**Comment by clgeros** [comment]
Great. Thanks!
