### ISSUE TITLE
Username and password to set up (2)

### ISSUE THREAD

**Issue by LucieGueuning** [usergroupcoop/msf-reach#75]
Username : natasha.reyes@hongkong.msf.org. Password : operators 
Username : remi.carrier@hongkong.msf.org. Password : viewers (can not edit – for the demo if we can only remove the ‘edit’ button only for this account, it should be great!)

**Comment by matthewberryman** [comment]
I will set up those users tomorrow with different passwords (for security reasons they can't be the same as anything we list publicly here, and also need to comply with password policies). Supporting different roles is a separate feature request I've opened in #79
