### ISSUE TITLE
REPLACE MAPS

### ISSUE THREAD

**Issue by clgeros** [usergroupcoop/msf-reach#76]
@mehrdadgit 
Please replace maps with the following:

Terrain/City Infrastructure link:
https://api.mapbox.com/styles/v1/clgeros/cj2lgdo3x000b2rmrv6iiii38/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY2xnZXJvcyIsImEiOiJjajBodHJjdGYwM21sMndwNHk2cGxxajRnIn0.nrw2cFsVqjA2bclnKs-9mw

Satellite Image Link:
https://api.mapbox.com/styles/v1/clgeros/cj2lds8kl00042smtdpniowm2/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY2xnZXJvcyIsImEiOiJjajBodHJjdGYwM21sMndwNHk2cGxxajRnIn0.nrw2cFsVqjA2bclnKs-9mw

**Comment by matthewberryman** [comment]
I will do this. @mehrdadgit please continue work on event fields.
