### ISSUE TITLE
Client: event page should zoom to extents

### ISSUE THREAD

**Issue by talltom** [usergroupcoop/msf-reach#8]
- generate extents from current reports in event
 - currently just zooming to event epicenter with fixed zoom level

**Comment by matthewberryman** [comment]
@LucieGueuning this is why you won't see reports on events page, unless you zoom out in which case they will show up on the map.

**Comment by matthewberryman** [comment]
Fixed with https://github.com/usergroupcoop/msf-reach/commit/770752c8a69c3c47d57bf3557ffd2d4442a1e781
