### ISSUE TITLE
New Report Icon

### ISSUE THREAD

**Issue by clgeros** [usergroupcoop/msf-reach#83]
@matthewberryman @mehrdadgit @talltom 

The current report icon just isn't working (visually) on the map. Can we please change this icon to:

https://drive.google.com/open?id=0Bw27FPU-gFxYNVlURFVoYWVSNU0

Will also send in an email in case the drive doesn't update.

**Comment by matthewberryman** [comment]
@mehrdadgit @talltom I will do this with other icon changes tomorrow a.m.
