### ISSUE TITLE
URGENT: Event Edit

### ISSUE THREAD

**Issue by clgeros** [usergroupcoop/msf-reach#92]
@mehrdadgit @matthewberryman 
When "editing" an event, we need to be able to "edit/change" the event status. This is a key component of the platform and demo. 
In this dialogue, (at minimum) STATUS (monitoring, assessment, intervention, complete) needs to be editable. If this is possible for tomorrow that would be great.

<img width="661" alt="screen shot 2017-08-24 at 11 46 12 am" src="https://user-images.githubusercontent.com/22763936/29648691-0b154bd8-88c2-11e7-9c0e-d53a9a4fe464.png">

**Comment by matthewberryman** [comment]
working
