### ISSUE TITLE
Edit function for current/open event information

### ISSUE THREAD

**Issue by clgeros** [usergroupcoop/msf-reach#96]
@matthewberryman in the "event information," we need a field for "latest notifications" which can always be edited by the creator of the event only (Natasha, at this point). In the "Edit" dialogue below, can we have a field for "name," "status," "security details," and "latest notifications."

<img width="661" alt="screen shot 2017-08-24 at 11 46 12 am" src="https://user-images.githubusercontent.com/22763936/29674701-839ae00a-8925-11e7-8df5-6c094d73a709.png">

**Comment by matthewberryman** [comment]
Also needs to be displayed - will put on pop up item and in event table on landing page for now.
